name: Shahmat CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: jgiven-reports

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get report
        uses: actions/download-artifact@v1
        with:
          name: report
    - name: Update github pages
      uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: report/jgiven-reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

